### ISSUE TITLE
Learning bits 6 to 8

### ISSUE THREAD

**Issue by alainvd** [codeeu/codeweek#376]
Add new learning bits

**Comment by alainvd** [comment]
Done in English

**Comment by raphdom** [comment]
Almost done, still missing some files:
Missing files:
Albanian - All activities and video scripts for the 5th firsts training modules
Bosnian - All activities and video scripts for the 5th firsts training modules
Danish - All activities and video scripts for the 6, 7, 8 training modules
Italian - The video script for the 5th firsts training modules
Maltese - The video script for the 5th firsts training modules
Polish - The video script for the 5th firsts training modules, the activities 1 and 2 for the second training module, the activity 3 for the fifty training module
