### ISSUE TITLE
Approve screen looks broken.

### ISSUE THREAD

**Issue by Grienauer** [codeeu/codeweek#512]
The layout of mobile view for approving codeweek events are broken. Example: https://codeweek.eu/view/213968/hackhaton-fur-gute-ki-good-ai

**Comment by Grienauer** [comment]
Here a screenshot.
Taken on my iPhone.
https://imgur.com/gallery/yHr5a6Z
Thx!

**Comment by alainvd** [comment]
@Grienauer Can you please retry ? we deployed a fix that should prevent this screen to be shown. Thanks.

**Comment by Grienauer** [comment]
it is still an issue on my side. ios (safari)
![UNADJUSTEDNONRAW_thumb_2705](https://user-images.githubusercontent.com/1458107/66774009-c5224600-eec0-11e9-8104-efeae34a0832.jpg)
![UNADJUSTEDNONRAW_thumb_2706](https://user-images.githubusercontent.com/1458107/66774010-c5224600-eec0-11e9-90ef-5bb39466fb2d.jpg)

**Comment by alainvd** [comment]
Can you try in Chrome ?

On my Android device I don't have Safari.



Le lun. 14 oct. 2019 à 20:26, Nico Grienauer <notifications@github.com> a
écrit :

**Comment by Grienauer** [comment]
currently we have no events to approve… will check it if an event comes in.
